[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BijectiveHilbert = "91e7fc40-53cd-4118-bd19-d7fcd1de2a54"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
BenchmarkTools = "1"
StaticArrays = "1"
