[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BijectiveHilbert = "91e7fc40-53cd-4118-bd19-d7fcd1de2a54"
GeometricalPredicates = "fd0ad045-b25c-564e-8f9c-8ef5c5f21267"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
BenchmarkTools = "1"
StaticArrays = "1"
