# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.4"
manifest_format = "2.0"
project_hash = "747c05f76b1058223a3afe3f04dcb0f451dbdb88"

[[deps.BijectiveHilbert]]
deps = ["TestItems"]
path = "."
uuid = "91e7fc40-53cd-4118-bd19-d7fcd1de2a54"
version = "0.6.0"

[[deps.StaticArraysCore]]
git-tree-sha1 = "6ab403037779dae8c514bad259f32a447262455a"
uuid = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
version = "1.4.4"

[[deps.TestItems]]
git-tree-sha1 = "42fd9023fef18b9b78c8343a4e2f3813ffbcefcb"
uuid = "1c621080-faea-4a02-84b6-bbd5e436b8fe"
version = "1.0.0"
