name = "BijectiveHilbert"
uuid = "91e7fc40-53cd-4118-bd19-d7fcd1de2a54"
version = "0.6.0"
authors = ["Andrew Dolgert <adolgert@andrew.cmu.edu>"]

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
BitIntegers = "0.3.7"
StaticArraysCore = "1.4.4"
TestItems = "^1.0"
julia = "1.7"
